controller_manager:
  ros__parameters:
    update_rate: 30

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    publish_rate: 50.0

    odom_frame_id: odom
    enable_odom_tf: true

    # This should match the xacro file.
    base_frame_id: carbody

    # This should match the joint names in the xacro file.
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    # This should match the wheel separation in the xacro file.
    wheel_separation: 0.15

    # This should match the wheel radius in the xacro file.
    wheel_radius: 0.028