# gz topic published by Sensors plugin (Depth Camera Info)
- ros_topic_name: "depth_camera/camera_info"
  gz_topic_name: "depth_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Depth Camera Points)
- ros_topic_name: "depth_camera/image_raw/points"
  gz_topic_name: "depth_camera/image_raw/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS